name: Learn GitHub Actions

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, World!
      - name: Run a one-line script
        run: echo Hello, World2!
      - name: Use configuration variable
        env:
          HOST_IP: ${{ vars.HOST_IP }}
        run: |
          echo "The URL is : $HOST_IP"
