name: Learn GitHub Actions

on:
  push:
    branches: ["main"]

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, World!
      - name: Run a one-line script
        run: echo Hello, World2!
      - name: Use configuration variable
        env:
          PORT: ${{ vars.PORT }}
        run: |
          echo "The URL test is : $PORT"
      - name: Use Environment variables
        run: echo "Host is ${{ env.HOST }}"
